### ISSUE TITLE
Legacy Code Addressed

### ISSUE THREAD

**Issue by courtneyanle** [cs169/fa23-chips-10.5-17#10]
due 11/25

**Comment by courtneyanle** [comment]
assignees are responsible for monitoring progress on this story, ensuring distinct issues are being addressed, outsourcing issues as necessary to other teammates

**Comment by jasonduongg** [comment]
Sent a pull request, and merged with permission from Vincent Do to master branch to allow for progression on his task under the branch feature/dup_reps
