### ISSUE TITLE
Rep Profile Addressed

### ISSUE THREAD

**Issue by courtneyanle** [cs169/fa23-chips-10.5-17#11]
due 11/25

**Comment by courtneyanle** [comment]
assignees are responsible for monitoring progress on this story, ensuring distinct issues are being addressed, outsourcing issues as necessary to other teammates

**Comment by jasonduongg** [comment]
Added most features, 
problems: 
api doenst populate the database using address, do we have to do this manually?
show page thinks rep is nil
